config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  get 'settings', action: 'index', controller: 'settings'
  get 'account', action: 'index', controller: 'account'

  # match 'tasks/list' => 'tasks#index', via: :post

  resources :tasks
  namespace :settings do
    resources :categories
    resources :tags
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    validates :is_done, presence: { if: lambda { is_done.nil? } }
    belongs_to :user
    belongs_to :category, optional: true
    has_many :tag_associations, dependent: :delete_all
    has_many :tags, through: :tag_associations
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    add_breadcrumb "Úkoly", :tasks_path
    def index
        # BEWARE: Default tasks have a `bell` character at the beginning of their title, so they appear before other tasks
        @list = List.new
        @tasks = @list.filter(params.has_key?("list") ? (task_filters) : nil, current_user)
        if params.has_key?(:list) && params[:list][:group_by] == "1"
            # Paginates by four categories because it can't count the tasks
            @tasks[:collection] = @tasks[:collection].paginate(page: params.has_key?(:page) ? params[:page] : 1, per_page: 4)
            @display_ungrouped = params[:page].to_i == @tasks[:collection].total_pages.to_i
            @display_ungrouped = true if @tasks[:collection].total_pages.to_i <= 1
        else @tasks = @tasks.paginate(page: params.has_key?(:page) ? params[:page] : 1, per_page: 30) end
    end
    def show
        @task = current_user.tasks.find(params[:id])
        add_breadcrumb @task.title
    end
    def new
        @task = current_user.tasks.new(is_done: false)
        add_breadcrumb "Nový úkol"
    end
    def edit
        @task = current_user.tasks.find(params[:id])
        add_breadcrumb @task.title
    end
    def create
        @task = current_user.tasks.new(task_params)
        if(@task.save) then redirect_to @task
        else render 'new' end
    end
    def update
        @task = current_user.tasks.find(params[:id])
        if(@task.update(task_params))
            if(params.has_key?("redirect_to_index") && params["redirect_to_index"]) then redirect_to tasks_path
            else redirect_to @task end
        else render 'edit' end
    end
    def destroy
        if(params.has_key?(:id) && params[:id].to_i > 0) 
            @task = current_user.tasks.find(params[:id])
            @task.destroy
        else
            d = params.require(:delete).permit!().to_hash().to_a().map { |i| i[0] if i[1].to_i > 0 }
            current_user.tasks.destroy(current_user.tasks.where(id: d))
        end
        redirect_to tasks_path
    end

    private
    def task_params
        params.require(:task).permit(:title, :note, :deadline_at, :category_id, :is_done, { tag_ids: [] })
    end
    def task_filters
                                                                                                                       # Because it just cannot be that simple, right, :is_done..?
        params.require(:list).permit(:search, { categories: [] }, { tags: [] }, :order_by, :order_direction, :group_by, {is_done: []})
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_back.html.erb
<%= link_to  (octicon("chevron-left")+" Zpět na přehled"), tasks_path, class: "btn btn-outline-light" %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |t| %>
    <% if @task.errors.any? { |e| e.length > 0 } %>
        <%= t.error_notification %>
        <% p @task.errors %>
    <% end %>
    <% rndtask = ["Koupit brambory", "Vyprat kalhoty", "Vyžehlit košili", "Zaplatit internet", "Odeslat semestrální práci", "Zabít draka"] %>
    <div class="input-text d-lg-none">Název: <%= octicon "primitive-dot" %></div>
    <div class="input-group">
        <div class="input-group-prepend d-none d-lg-flex">
            <span class="input-group-text">Název <%= octicon "primitive-dot" %></span>
        </div>
        <%= t.input_field :title,
                    required: true,
                    placeholder: "např. '#{rndtask[rand(0..rndtask.length-1)]}'",
                    class: "form-control" %>
    </div>
    <div class="input-text d-lg-none">Poznámka:</div>
    <div class="input-group">
        <div class="input-group-prepend d-none d-lg-flex">
            <span class="input-group-text">Poznámka</span>
        </div>
        <%= t.input_field :note,
                    class: "form-control" %>
    </div>
    <div class="input-text d-lg-none">Splnit do:</div>
    <div class="input-group">
        <div class="input-group-prepend d-none d-lg-flex">
            <span class="input-group-text">Splnit do</span>
        </div>
        <%= t.input_field :deadline_at,
                    as: :string,
                    class: "form-control" %>
    </div>
    <div class="input-text d-lg-none">Kategorie:</div>
    <div class="input-group">
        <div class="input-group-prepend d-none d-lg-flex">
            <span class="input-group-text">Kategorie</span>
        </div>
        <%= t.association :category,
                    required: false,
                    label: false,
                    wrapper: false,
                    collection: current_user.categories,
                    class: "form-control" %>
    </div>
    <div class="input-text d-lg-none">Značky:</div>
    <div class="input-group">
        <div class="input-group-prepend d-none d-lg-flex">
            <span class="input-group-text">Značky</span>
        </div>
        <div class="form-control collection-wrap">
            <%= t.association :tags,
                        collection: current_user.tags,
                        required: false,
                        legend: false,
                        as: :check_boxes,
                        wrapper: false,
                        class: "col" %>
        </div>
    </div>
    <%= t.input :is_done,
                as: :hidden %>
    <div class="d-sm-flex justify-content-between">
        <%= link_to  "Zrušit", tasks_path, class: "btn btn-outline-secondary" %>
        <%= t.submit "Uložit", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/tasks/_task_entity.html.erb
<div class="list-group-item">
    <div class="d-flex justify-content-left">
        <%= simple_form_for(task) do |t| %>
            <label class="task-done-state<%= task.is_done ? " active" : "" %>">
                <%= octicon "check" %>
            </label>
            <%= t.input_field :is_done,
                        class: "task-change-state",
                        id: "task_is_done_#{t.object.id}" %>
            <input type="hidden" name="redirect_to_index" value="true" />
        <% end %>
        <h3><%= task.title.gsub(7.chr, "") %></h3>
    </div>
    <p class="task-info">
    <% if !task.deadline_at.nil? %>
        <span>
            <%= octicon "clock" %>
            <%= task.deadline_at.strftime "%d. %m. %Y" %>
        </span>
    <% end %>
    <% if !task.category.nil? && task.category.id > 0 %>
        <span>
            <%= link_to  (octicon("saved")+"#{task.category.title}"), settings_category_path(task.category), "data-entity-color": task.category.color, class: "category-link" %>
        </span>
    <% end %>
    <% if task.tags.length > 0 %>
        <span>
        <% if task.tags.length > 4 then tag_render = task.tags.to_ary.slice(0,4) else tag_render = task.tags end %>
        <% tag_render.each do |g| %>
            <span class="tag-link" data-entity-color="<%= g.color %>">
                <%= octicon "tag", class: "back-icon" %>
                <%= link_to  g.title, settings_tag_path(g) %>
            </span>
        <% end %>
        <% if task.tags.length > 4 %>
            <span class="tag-link">
                <%= "+#{task.tags.length - 4}" %>
            </span>
        <% end %>
        </span>
    <% end %>
    <% if !task.note.nil? && task.note != "" %>
        <span class="text-muted">
            <%= octicon "comment" %>
            <% if task.note.lines.length > 1 %>
                <%= "#{task.note.lines[0][0..24]}..." %>
            <% else %>
                <%= task.note.lines[0].length > 24 ? "#{task.note.lines[0][0..24]}..." : task.note.lines[0] %>
            <% end %>
        </span>
    <% end %>
    </p>
    <div>
        <% unless multi.nil? %>
            <%= multi.input_field task.id,
                            as: :boolean,
                            form: "multi-delete",
                            class: "mdi" %>
        <% end %>
        <%= link_to 'Více...', task %>
        <%= link_to 'Upravit', edit_task_path(task) %>
        <%= link_to 'Odstranit', task, method: :delete, data: { confirm: 'Opravdu si přejete úkol odstranit?' } %>
    </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
    <div class="form-inputs">
        <h1>Upravit '<%= @task.title %>'</h1>
        <%= render "form" %>
    </div>
</div>

app/views/tasks/index.html.erb
<h1>Úkoly</h1>
<div class="list-group">
    <div class="list-group list-group-horizontal">
        <%= link_to new_task_path, class: "list-group-item list-group-item-action btn-link" do %>
            <%= octicon "plus" %>
            Přidat
            <span class="d-none d-md-inline">nový úkol</span>
        <% end %>
        <button type="button" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" data-toggle="modal" data-target="#sort-modal">
            <%= octicon "settings" %>
            <span class="d-none d-lg-inline">
                Seřadit a seskupit...
            </span>
            &zwnj;
            <% if @list.sorted? %>
                <span class="badge badge-pill badge-primary">
                    <%= octicon "chevron-#{@list.order_direction == "asc" ? "up" : "down"}" %>
                </span>
            <% end %>
        </button>
        <button type="button" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" data-toggle="modal" data-target="#filter-modal">
            <%= octicon "search" %>
            <span class="d-none d-lg-inline">
                Filtrovat...
            </span>
            &zwnj;
            <% if @list.filter_count > 0 %>
                <span class="badge badge-pill badge-<%= @list.group_by ? "secondary" : "primary" %>">
                    <%= @list.filter_count %>
                </span>
            <% end %>
        </button>
    </div>
<%= simple_form_for(@list, url: tasks_path, method: :get) do |f| %>
    <div class="modal fade" role="dialog" id="filter-modal">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Filtrovat...</h5>
                    <button class="close" role="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <%= f.input :search,
                                as: :string,
                                autocomplete: false,
                                label: "Hledat" %>
                    <div>
                        <h6>Podle kategorie</h6>
                        <div class="collection-wrap">
                            <input type="hidden" id="categories_selected" value="<%= f.object.categories.to_s.dump %>">
                            <%= f.input :categories,
                                        as: :check_boxes,
                                        collection: current_user.categories,
                                        wrapper: false %>
                        </div>
                    </div>
                    <div>
                        <h6>Podle značek</h6>
                        <div class="collection-wrap">
                            <input type="hidden" id="tags_selected" value="<%= f.object.tags.to_s.dump %>">
                            <%= f.input :tags,
                                        as: :check_boxes,
                                        collection: current_user.tags,
                                        selected: f.object.tags,
                                        wrapper: false %>
                        </div>
                    </div>
                    <div>
                        <h6>Podle stavu</h6>
                        <div class="collection-wrap">
                            <input type="hidden" id="is_done_selected" value="<%= f.object.is_done %>">
                            <%= f.input :is_done,
                                        as: :check_boxes,
                                        collection: [["Dokončené", true], ["Otevřené", false]],
                                        class: "check-single form-check",
                                        label_method: :first,
                                        value_method: :second,
                                        wrapper: false %>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <%= f.submit "Filtrovat",
                                  class: "btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" role="dialog" id="sort-modal">
        <div class="modal-dialog modal-dialog-scroll" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Seřadit...</h5>
                    <button class="close" role="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <%= f.input :order_by,
                                as: :radio_buttons,
                                collection: [["Názvu", :title], ["Termínu splnění", :deadline_at]],
                                label_method: :first,
                                value_method: :second,
                                label: "Seřadit podle" %>
                    <%= f.input :order_direction,
                                as: :radio_buttons,
                                collection: [["Vzestupně", "asc"], ["Sestupně", "desc"]],
                                label_method: :first,
                                value_method: :second,
                                label: "",
                                checked: @list.empty? ? "desc" : @list.order_direction %>
                </div>
                <div class="modal-header">
                    <h5 class="modal-title">Seskupit...</h5>
                </div>
                <div class="modal-body">
                    <%= f.input :group_by,
                                as: :boolean,
                                label: "Seskupit podle kategorií" %>
                </div>
                <div class="modal-footer">
                    <%= f.submit "Seřadit a seskupit",
                                 class: "btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>
<% end %>
<% unless @list.group_by %>
    <%= simple_form_for :delete, url: task_path(-1), html: {method: :delete, id: "multi-delete"} do |t|
            @mdf = t
        end %>
    <% @tasks.each do |task| %>
        <% task.tags.order!(title: "ASC") %>
        <%= render partial: "task_entity", locals: { task: task, multi: @mdf } %>
    <% end %>
    <% if @tasks.count > 0 %>
    <button class="btn btn-link" id="multiple-destroy-call" data-toggle="modal" data-target="#multiple-destroy-modal">Odstranit vybrané</button>
    <div class="modal fade" role="dialog" id="multiple-destroy-modal">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Opravdu si přejete odstranit všechny vybrané úkoly?</h5>
                    <button class="close" role="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body d-flex justify-content-around">
                <button class="btn btn-primary" data-dismiss="modal">Zrušit</button>
                <%= @mdf.submit "Odstranit vybrané",
                                class: "btn btn-outline-danger",
                                form: "multi-delete" %>
                </div>
            </div>
        </div>
    </div>
    <% end %>
<% else %>
    <% @tasks[:collection].each do |category| %>
        <% next unless category.tasks.count > 0 %>
        <% category.tasks.order!("deadline_at IS NOT NULL").order!(deadline_at: "ASC") %>
        <div class="list-group-item">
            <div class="task-info">
                <h4>
                    <span>
                        <%= link_to  (octicon("saved")+"#{category.title}"), settings_category_path(category), "data-entity-color": category.color, class: "category-link" %>
                    </span>
                </h4>
            </div>
            <div class="list-group">
                <% category.tasks.each do |task| %>
                    <% task.tags.order!(title: "ASC") %>
                    <%= render partial: "task_entity", locals: { task: task, multi: nil } %>
                <% end %>
            </div>
        </div>
    <% end %>
    <% if @display_ungrouped %>
    <div class="list-group-item">
        <div class="task-info">
            <h4>Nezařazené</h4>
        </div>
        <div class="list-group">
            <% @tasks[:ungrouped].each do |task| %>
                <% task.tags.order!(title: "ASC") %>
                <%= render partial: "task_entity", locals: { task: task, multi: nil } %>
            <% end %>
        </div>
    </div>
    <% end %>
<% end %>
<% if @tasks.count <= 0 %>
    <div class="list-group-item">
        <h4>
            <% unless @list.empty? %>
                Tento filtr nevrátil žádné výsledky
            <% else %>
                Nemáte žádné úkoly
            <% end %>
        </h4>
        <div>
            <%= link_to  "Vytvořit nový úkol", new_task_path %>
            <% unless @list.empty? %>
                nebo
                <%= link_to  "zrušit filtry", tasks_path %>
            <% end %>
        </div>
    </div>
<% end %>
<% if @list.group_by %>
<%= will_paginate @tasks[:collection], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<% else %>
<%= will_paginate @tasks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
    <%= render "back" %>
    <div class="form-inputs">
        <h1>Nový úkol</h1>
        <%= render "form" %>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
    <%= render "back" %>
    <div class="card task-entity">
        <div class="card-body">
            <div class="card-title d-sm-flex justify-content-left align-items-center">
                <%= simple_form_for(@task) do |t| %>
                    <label class="task-done-state<%= @task.is_done ? " active" : "" %>">
                        <%= octicon "check" %>
                    </label>
                    <%= t.input_field :is_done,
                                class: "task-change-state" %>
                <% end %>
                <h1><%= @task.title %></h1>
            </div>
            <div class="card-text task-info">
                <h5>
                    <%= @task.note %>
                </h5>
                <div class="d-sm-flex justify-content-around">
                    <div>
                        #
                        <%= @task.id %>
                    </div>
                    <div>
                        <%= octicon "plus" %>
                        <%= @task.created_at.strftime("%d. %m. %Y") %>
                    </div>
                    <div>
                        <%= octicon "pencil" %>
                        <%= @task.updated_at.strftime("%d. %m. %Y") %>
                    </div>
                    
                </div>
                <% if !@task.deadline_at.nil? %>
                    <p>
                        <strong>Splnit do: </strong>
                        <%= octicon "clock" %>
                        <%= @task.deadline_at.strftime "%d. %m. %Y" %>
                    </p>
                <% end %>
                <% if !@task.category.nil? %>
                    <p>
                        <strong>Kategorie: </strong>
                        <%= link_to  (octicon("saved")+"#{@task.category.title}"), settings_category_path(@task.category), "data-entity-color": @task.category.color, class: "category-link" %>
                    </p>
                <% end %>
                <% if @task.tags.length > 0 %>
                    <p class="">
                        <strong>Značky: </strong>
                    <% @task.tags.each do |g| %>
                        <span class="tag-link" data-entity-color="<%= g.color %>">
                            <%= octicon "tag", class: "back-icon" %>
                            <%= link_to  g.title, settings_tag_path(g) %>
                        </span>
                    <% end %>
                    </p>
                <% end %>
                <%= link_to  "Upravit", edit_task_path(@task), class: "card-link" %>
                <%= link_to  "Odstranit", task_path(@task), method: :delete, class: "card-link", data: { confirm: 'Opravdu si přejete úkol odstranit?' } %>
            </div>
        </div>
    </div>
</div>