config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  get 'settings', action: 'index', controller: 'settings'
  get 'account', action: 'index', controller: 'account'

  # match 'tasks/list' => 'tasks#index', via: :post

  resources :tasks
  namespace :settings do
    resources :categories
    resources :tags
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true
    validates :color, presence: true
    belongs_to :user
    has_many :tag_associations, dependent: :delete_all
    has_many :tasks, through: :tag_associations
end

app/controllers/settings/categories_controller.rb
class Settings::CategoriesController < ApplicationController
    before_action :authenticate_user!, :settings_categories_path, only: [:show, :edit, :update, :destroy]
    add_breadcrumb "Nastavení", :settings_path
    add_breadcrumb "Kategorie", :settings_categories_path
    def index
        # BEWARE: Default categories have a `bell` character at the beginning of their title, so they appear before other categories
        @categories = current_user.categories.all.includes(:tasks).order(:title)
    end
    def show
        @category = current_user.categories.find(params[:id])
        add_breadcrumb @category.title
    end
    def new
        @category = current_user.categories.new
        @save_path = settings_categories_path
        add_breadcrumb "Nová kategorie"
    end
    def edit
        @category = current_user.categories.find(params[:id])
        @save_path = settings_category_path(@category)
        add_breadcrumb @category.title
    end
    def create
        @category = current_user.categories.new(category_params)
        if(@category.save) then redirect_to settings_categories_path
        else render 'new' end
    end
    def update
        @category = current_user.categories.find(params[:id])
        if(@category.update(category_params)) then redirect_to settings_category_path(@category)
        else render 'edit' end
    end
    def destroy
        @category = current_user.categories.find(params[:id])
        @category.tasks.update(category_id: nil)
        @category.destroy
        redirect_to settings_categories_path
    end

    private
    def category_params
        params.require(:category).permit(:title, :color)
    end
end

app/controllers/settings/tags_controller.rb
class Settings::TagsController < ApplicationController
    before_action :authenticate_user!, :settings_tags_path, only: [:show, :edit, :update, :destroy]
    add_breadcrumb "Nastavení", :settings_path
    add_breadcrumb "Značky", :settings_tags_path
    def index
        # BEWARE: Default tags have a `bell` character at the beginning of their title, so they appear before other tags
        @tags = current_user.tags.all.includes(:tag_associations, :tasks).order(:title)
    end
    def show
        @tag = current_user.tags.find(params[:id])
        add_breadcrumb @tag.title
    end
    def new
        @tag = Tag.new
        @save_path = settings_tags_path
        add_breadcrumb "Nová značka"
    end
    def edit
        @tag = current_user.tags.find(params[:id])
        @save_path = settings_tag_path(@tag)
        add_breadcrumb @tag.title
    end
    def create
        p params
        @tag = current_user.tags.new(tag_params)
        if(@tag.save) then redirect_to settings_tags_path
        else render 'new' end
    end
    def update
        @tag = current_user.tags.find(params[:id])
        if(@tag.update(tag_params)) then redirect_to settings_tag_path(@tag)
        else render 'edit' end
    end
    def destroy
        @tag = current_user.tags.find(params[:id])
        @tag.destroy
        redirect_to settings_tags_path
    end

    private
    def tag_params
        params.require(:tag).permit(:title, :color)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  add_breadcrumb "Nastavení", :settings_path
  def index
  end
end

app/helpers/settings/categories_helper.rb
module Settings::CategoriesHelper
end

app/helpers/settings/tags_helper.rb
module Settings::TagsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/tags/_back.html.erb
<%= link_to  (octicon("chevron-left")+" Zpět na přehled"), settings_tags_path, class: "btn btn-outline-light" %>

app/views/settings/tags/_form.html.erb
<%= simple_form_for(@tag, url: @save_path) do |t| %>
        <% if @tag.errors.any? { |e| e.length > 0 } %>
            <%= t.error_notification %>
            <% p @tag.errors %>
        <% end %>
        <div class="input-text d-lg-none">Název značky: <%= octicon "primitive-dot" %></div>
        <div class="input-group">
            <div class="input-group-prepend d-none d-lg-flex">
                <span class="input-group-text">Název značky <%= octicon "primitive-dot" %></span>
            </div>
            <%= t.input_field :title,
                        required: true,
                        autofocus: true,
                        placeholedr: "např. 'Práce'",
                        class: "form-control" %>
        </div>
        <br />
        <div class="input-text d-lg-none">Barva: <%= octicon "primitive-dot" %></div>
        <div class="input-group">
            <div class="input-group-prepend d-none d-lg-flex">
                <span class="input-group-text">Barva <%= octicon "primitive-dot" %></span>
            </div>
            <%= t.input_field :color,
                        as: :color,
                        required: true,
                        class: "form-control" %>
        </div>
        <br />
        <%= t.button :submit, "Uložit", class: "btn btn-primary" %>
<% end %>

app/views/settings/tags/edit.html.erb
<div class="container">
    <%= render "back" %>
    <div class="form-inputs">
        <h1>Upravit značku <%= @tag.title %></h1>
        <%= render "form" %>
    </div>
</div>

app/views/settings/tags/index.html.erb
<h1>Značky</h1>
<div class="row">
    <div class="col-lg-4 col-sm-12">
        <div class="card task-entity">
            <div class="card-body">
                <%= link_to  octicon("plus", {class:"btn-link"})+" Nová značka", new_settings_tag_path, class: "card-link" %>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
<% if @tags.count > 0 %>
<% @tags.each do |tag| %>
    <div class="col-lg-4 col-sm-12">
        <div class="card task-entity" data-entity-color="<%= tag.color %>">
            <%= octicon "tag", class: "back-icon" %>
            <div class="card-body">
                <div class="card-title d-flex justify-content-between">
                    <h5><%= tag.title %></h5>
                    <div class="text-muted small"><%= tag.tasks.length %> označených</div>
                </div>
                <div class="card-text d-none justify-content-around d-md-flex">
                    <div class="small">#<%= tag.id %></div>
                    <div class="small"><%= octicon "plus" %> <%= tag.created_at.strftime("%d. %m. %Y") %></div>
                    <div class="small"><%= octicon "pencil" %> <%= tag.updated_at.strftime("%d. %m. %Y") %></div>
                    <div class="text-monospace small">
                        <span style="color: <%= tag.color %>;">&#9608;&#9608;</span>
                        rgb(<%= "#{tag.color[1..2].to_i(16)},#{tag.color[3..4].to_i(16)},#{tag.color[5..6].to_i(16)}" %>)
                    </div>
                </div>
                <div class="card-rud-links">
                    <%= link_to  "Detail", settings_tag_path(tag), class: "card-link" %>
                    <%= link_to  "Upravit", edit_settings_tag_path(tag), class: "card-link" %>
                    <%= link_to  "Odstranit", settings_tag_path(tag), method: :delete, class: "card-link", data: { confirm: 'Opravdu si přejete značku odstranit?' } %>
                </div>
            </div>
        </div>
    </div>
<% end %>
<% else %>
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4>Nemáte žádné značky</h4>
                <%= link_to  "Vytvořit novou značku", new_settings_tag_path %>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/settings/tags/new.html.erb
<div class="container">
    <%= render "back" %>
    <div class="form-inputs">
        <h1>Nová značka</h1>
        <%= render "form" %>
    </div>
</div>

app/views/settings/tags/show.html.erb
<div class="container">
    <%= render "back" %>
    <div class="card task-entity" data-entity-color="<%= @tag.color %>">
        <%= octicon "tag", class: "back-icon" %>
        <div class="card-body">
            <div class="card-title">
                <h1><%= @tag.title %></h1>
            </div>
            <p class="card-text">
            <div class="d-sm-flex justify-content-around">
                    <div>
                        #
                        <%= @tag.id %>
                    </div>
                    <div>
                        <%= octicon "plus" %>
                        <%= @tag.created_at.strftime("%d. %m. %Y") %>
                    </div>
                    <div>
                        <%= octicon "pencil" %>
                        <%= @tag.updated_at.strftime("%d. %m. %Y") %>
                    </div>
                    
                </div>
        <% if @tag.tasks.length <= 0 %>
            Tato značka zatím nebyla přiřazena k žádnému úkolu
        <% else %>
            Přiřazeno k <%= @tag.tasks.length %> úkolům
        <% end %>
            </p>
            <%= link_to  "Upravit", edit_settings_tag_path(@tag), class: "card-link" %>
            <%= link_to  "Odstranit", settings_tag_path(@tag), method: :delete, class: "card-link", data: { confirm: 'Opravdu si přejete značku odstranit?' } %>
        </div>
    <% if @tag.tasks.length > 0 %>
        <ul class="list-group list-group-flush">
        <% @tag.tasks.each do |t| %>
            <li class="list-group-item">
                <div><%= t.title %></div>
                <div><%= link_to  "Zobrazit detail úkolu", task_path(t), class: "card-link" %><div>
            </li>
        <% end %>
        </ul>
    <% end %>
    </div>
</div>