config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  get 'settings', action: 'index', controller: 'settings'
  get 'account', action: 'index', controller: 'account'

  # match 'tasks/list' => 'tasks#index', via: :post

  resources :tasks
  namespace :settings do
    resources :categories
    resources :tags
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<header class="home-tagline-header">
    <div class="home-light-theme">
        <h1>Úkoly pod kontrolou</h1>
        <h2>s aplikací TaskList</h2>
    </div>
    <% if user_signed_in? %>
        <div class="d-flex justify-content-around">
            <%= link_to  "Nastavení", settings_path, class: "btn btn-link" %>
            <%= link_to  "Moje úkoly", tasks_path, class: "btn btn-primary" %>
            <%= link_to  "Odhlásit se", destroy_user_session_path, method: :delete, class: "btn btn-link" %>
        </div>
    <% else %>
        <div class="column-align">
            <%= link_to  "Přihlásit se", new_user_session_path, class: "btn btn-primary" %>
            <%= link_to  "Ještě nemáte účet?", new_user_registration_path %>
        </div>
    <% end %>
    <div class="home-dark-theme">
        <p>Aplikace TaskList umožňuje jednoduchou správu úkolů z prostředí webového prohlížeče.</p>
        <p>Klíčové vlastnosti:</p>
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="point-block">
                    <%= octicon 'saved', "aria-label" => "Kategorie" %>
                    Kategorie
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="point-block">
                    <%= octicon 'tag', "aria-label" => "Značky" %>
                    Značky
                </div>
            </div>
            <div class="col-12 col-md-4" id="rainbow-bitch">
                <div class="point-block">
                    <!-- https://ih1.redbubble.net/image.428495307.9315/poster,840x830,f8f8f8-pad,750x1000,f8f8f8.jpg -->
                    <!-- <%= octicon 'paintcan', "aria-label" => "Barvičky" %>  -->
                    <span>B</span>
                    <span>a</span>
                    <span>r</span>
                    <span>v</span>
                    <span>i</span>
                    <span>č</span>
                    <span>k</span>
                    <span>y</span>
                </div>
            </div>
        </div>
    </div>
</header>